service: serverless-google-auth-login

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
useDotenv: true
provider:
  name: aws
  runtime: python3.10

functions:
  apiloginexample:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    environment:
      OAUTH_CLIENT_ID: ${env.OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
      LAMBDA_URL: ${env.LAMBDA_URL}
plugins:
  - serverless-wsgi
  - serverless-python-requirements
